services:
  web:
    build:
      context: ./docker/web
      dockerfile: Dockerfile
    ports:
      - "8000:80"
    volumes:
      - ./src:/var/www/html
      - ./docker/web/:/etc/nginx/conf.d
    depends_on:
      - app

  app:
    build:
      context: ./docker/app
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    volumes:
      - ./src:/var/www/html

  db:
    image: mysql:latest
    ports:
      - 3306:3306
    volumes:
      - ./docker/db/my.cnf:/etc/mysql/conf.d/my.cnf
      - db-store:/var/lib/mysql
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
  
volumes:
  db-store:
